name: "Build reviewdog"
description: "Build and run patched reviewdog version"

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
          sudo apt install -y golang-go git
    - name: Download reviewdog source code
      shell: bash
      run: |
          git clone https://github.com/reviewdog/reviewdog
          cd reviewdog
    - name: Patch and build reviewdog
      shell: bash
      run: |
          cd reviewdog
          git apply ${{ github.action_path }}/reviewdog.patch
          sudo go build -o /usr/local/bin/ ./cmd/reviewdog
    - name: Check reviewdog version
      shell: bash
      run: |
          reviewdog --version
